version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret-password
      MYSQL_DATABASE: testBd
      MYSQL_USER: microservice
      MYSQL_PASSWORD: secre
  web:
    build: .
    ports:
      - "8080:8080"